#!/usr/bin/env python3
import socket
import struct
import sys

# connection constants
HOST = '127.0.0.1'
PORT = 54901

def send_line(line):

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
        # connect to server
        client_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        client_socket.connect((HOST, PORT))
    
        # check that the line is not an empty line
        if line.strip():
            data = b'A' + len(line).to_bytes(4, byteorder='big') + line.encode()
            client_socket.sendall(data)
    
        # close socket
        client_socket.shutdown(socket.SHUT_RDWR)
        client_socket.close()


if __name__ == '__main__':

    # wrong number of parameters
    if (len(sys.argv) != 2):
        sys.exit(1)

    # get input file name
    input_file = sys.argv[1]

    # open and read each file line and send it
    with open(sys.argv[1], 'r') as file:

        for line in file:

            # send the read line
            send_line(line)

        # send termination signal
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
            # connect to server
            client_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            client_socket.connect((HOST, PORT))
            
            # send 0 to server
            client_socket.sendall(b'A' + b'\x00\x00\x00\x00')